**LOGISTIC REGRESSION**

In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#load dataset
dataset = pd.read_csv('/content/kidney_disease.csv')
# dataset
dataset = dataset.dropna()
# without_missing

In [ ]:
X=dataset.iloc[:,0:5].values
y=dataset.iloc[:,5].values

In [ ]:
from sklearn.model_selection import train_test_split
XTrain,XTest,yTrain,yTest=train_test_split(X,y,test_size=0.20,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
XTrain=sc.fit_transform(XTrain)
XTest=sc.fit_transform(XTest)

In [ ]:
dataset.count()

id                158
age               158
bp                158
sg                158
al                158
su                158
rbc               158
pc                158
pcc               158
ba                158
bgr               158
bu                158
sc                158
sod               158
pot               158
hemo              158
pcv               158
wc                158
rc                158
htn               158
dm                158
cad               158
appet             158
pe                158
ane               158
classification    158
dtype: int64

In [ ]:
missing_data=dataset.isnull().sum()

In [ ]:
missing_data

id                0
age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Train a logistic regression classifier
classifier = LogisticRegression()
classifier.fit(XTrain, yTrain)

# Make predictions on the test set
yPred = classifier.predict(XTest)

# Calculate confusion matrix
conf_matrix = confusion_matrix(yTest, yPred)

# Calculate other metrics
accuracy = accuracy_score(yTest, yPred)
precision = precision_score(yTest, yPred, average='micro')  # Use 'micro', 'macro', or 'weighted'
recall = recall_score(yTest, yPred, average='micro')  # Use 'micro', 'macro', or 'weighted'
f1 = f1_score(yTest, yPred, average='micro')  # Use 'micro', 'macro', or 'weighted'

# Print the results
print("Confusion Matrix:")
print(conf_matrix)
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")


Confusion Matrix:
[[30  0  0]
 [ 0  0  0]
 [ 0  2  0]]
Accuracy: 0.9375
Precision: 0.9375
Recall: 0.9375
F1-score: 0.9375


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Train a logistic regression classifier
classifier = LogisticRegression()
classifier.fit(XTrain, yTrain)

# Make predictions on the test set
yPred_prob = classifier.predict_proba(XTest)[:, 1]  # Probability of positive class
threshold = 0.5
binary_predictions = (yPred_prob > threshold).astype(int)

# Calculate confusion matrix
conf_matrix = confusion_matrix(yTest, binary_predictions)

# Calculate other metrics
accuracy = accuracy_score(yTest, binary_predictions)
precision = precision_score(yTest, binary_predictions, average='micro')  # Use 'micro', 'macro', or 'weighted'
recall = recall_score(yTest, binary_predictions, average='micro')  # Use 'micro', 'macro', or 'weighted'
f1 = f1_score(yTest, binary_predictions, average='micro')  # Use 'micro', 'macro', or 'weighted'

# Print the results
print("Confusion Matrix:")
print(conf_matrix)
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")


Confusion Matrix:
[[30  0]
 [ 2  0]]
Accuracy: 0.9375
Precision: 0.9375
Recall: 0.9375
F1-score: 0.9375


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

threshold = 0.5
binary_predictions = (yPred > threshold).astype(int)

# Flatten XTest if it's not already 1D
XTest_flat = XTest.ravel()

# Calculate accuracy
accuracy = accuracy_score(XTest_flat, binary_predictions)

# Calculate precision, recall, and F1-score
precision = precision_score(test_labels, binary_predictions)
recall = recall_score(test_labels, binary_predictions)
f1 = f1_score(test_labels, binary_predictions)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")


ValueError: ignored

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

threshold = 0.5
binary_predictions = (yPred > threshold).astype(int)

# Calculate accuracy
accuracy = accuracy_score(test_labels, binary_predictions)

# Calculate precision, recall, and F1-score
precision = precision_score(test_labels, binary_predictions)
recall = recall_score(test_labels, binary_predictions)
f1 = f1_score(test_labels, binary_predictions)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

NameError: ignored

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(XTrain,yTrain)

LogisticRegression()

In [ ]:
yPred=classifier.predict(XTest)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(yTest,yPred)

array([[30,  0,  0],
       [ 0,  0,  0],
       [ 0,  2,  0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(yTest,yPred)

0.9375

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

threshold = 0.5
binary_predictions = (prediction > threshold).astype(int)

# Calculate accuracy
accuracy = accuracy_score(test_labels, binary_predictions)

# Calculate precision, recall, and F1-score
precision = precision_score(test_labels, binary_predictions)
recall = recall_score(test_labels, binary_predictions)
f1 = f1_score(test_labels, binary_predictions)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")

NameError: ignored

In [ ]:
yPred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [ ]:
yTest

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 2., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0.])